/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardQueuesRouteImport } from './routes/_dashboard/queues'
import { Route as DashboardConnectionsRouteImport } from './routes/_dashboard/connections'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as DashboardSettingsConnectionsRouteImport } from './routes/_dashboard/settings/connections'
import { Route as DashboardQueuesQueueNameRouteImport } from './routes/_dashboard/queues.$queueName'
import { Route as DashboardConnectionsConnectionIdRouteImport } from './routes/_dashboard/connections.$connectionId'
import { Route as DashboardSettingsConnectionsNewRouteImport } from './routes/_dashboard/settings/connections.new'
import { Route as DashboardSettingsConnectionsConnectionIdEditRouteImport } from './routes/_dashboard/settings/connections.$connectionId.edit'
import { Route as DashboardConnectionsConnectionIdQueuesQueueNameRouteImport } from './routes/_dashboard/connections.$connectionId.queues.$queueName'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardQueuesRoute = DashboardQueuesRouteImport.update({
  id: '/queues',
  path: '/queues',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardConnectionsRoute = DashboardConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsConnectionsRoute =
  DashboardSettingsConnectionsRouteImport.update({
    id: '/settings/connections',
    path: '/settings/connections',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardQueuesQueueNameRoute =
  DashboardQueuesQueueNameRouteImport.update({
    id: '/$queueName',
    path: '/$queueName',
    getParentRoute: () => DashboardQueuesRoute,
  } as any)
const DashboardConnectionsConnectionIdRoute =
  DashboardConnectionsConnectionIdRouteImport.update({
    id: '/$connectionId',
    path: '/$connectionId',
    getParentRoute: () => DashboardConnectionsRoute,
  } as any)
const DashboardSettingsConnectionsNewRoute =
  DashboardSettingsConnectionsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => DashboardSettingsConnectionsRoute,
  } as any)
const DashboardSettingsConnectionsConnectionIdEditRoute =
  DashboardSettingsConnectionsConnectionIdEditRouteImport.update({
    id: '/$connectionId/edit',
    path: '/$connectionId/edit',
    getParentRoute: () => DashboardSettingsConnectionsRoute,
  } as any)
const DashboardConnectionsConnectionIdQueuesQueueNameRoute =
  DashboardConnectionsConnectionIdQueuesQueueNameRouteImport.update({
    id: '/queues/$queueName',
    path: '/queues/$queueName',
    getParentRoute: () => DashboardConnectionsConnectionIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/connections': typeof DashboardConnectionsRouteWithChildren
  '/queues': typeof DashboardQueuesRouteWithChildren
  '/connections/$connectionId': typeof DashboardConnectionsConnectionIdRouteWithChildren
  '/queues/$queueName': typeof DashboardQueuesQueueNameRoute
  '/settings/connections': typeof DashboardSettingsConnectionsRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/settings/connections/new': typeof DashboardSettingsConnectionsNewRoute
  '/connections/$connectionId/queues/$queueName': typeof DashboardConnectionsConnectionIdQueuesQueueNameRoute
  '/settings/connections/$connectionId/edit': typeof DashboardSettingsConnectionsConnectionIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/connections': typeof DashboardConnectionsRouteWithChildren
  '/queues': typeof DashboardQueuesRouteWithChildren
  '/connections/$connectionId': typeof DashboardConnectionsConnectionIdRouteWithChildren
  '/queues/$queueName': typeof DashboardQueuesQueueNameRoute
  '/settings/connections': typeof DashboardSettingsConnectionsRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/settings/connections/new': typeof DashboardSettingsConnectionsNewRoute
  '/connections/$connectionId/queues/$queueName': typeof DashboardConnectionsConnectionIdQueuesQueueNameRoute
  '/settings/connections/$connectionId/edit': typeof DashboardSettingsConnectionsConnectionIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/_dashboard/connections': typeof DashboardConnectionsRouteWithChildren
  '/_dashboard/queues': typeof DashboardQueuesRouteWithChildren
  '/_dashboard/connections/$connectionId': typeof DashboardConnectionsConnectionIdRouteWithChildren
  '/_dashboard/queues/$queueName': typeof DashboardQueuesQueueNameRoute
  '/_dashboard/settings/connections': typeof DashboardSettingsConnectionsRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_dashboard/settings/connections/new': typeof DashboardSettingsConnectionsNewRoute
  '/_dashboard/connections/$connectionId/queues/$queueName': typeof DashboardConnectionsConnectionIdQueuesQueueNameRoute
  '/_dashboard/settings/connections/$connectionId/edit': typeof DashboardSettingsConnectionsConnectionIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/connections'
    | '/queues'
    | '/connections/$connectionId'
    | '/queues/$queueName'
    | '/settings/connections'
    | '/api/auth/$'
    | '/settings/connections/new'
    | '/connections/$connectionId/queues/$queueName'
    | '/settings/connections/$connectionId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/connections'
    | '/queues'
    | '/connections/$connectionId'
    | '/queues/$queueName'
    | '/settings/connections'
    | '/api/auth/$'
    | '/settings/connections/new'
    | '/connections/$connectionId/queues/$queueName'
    | '/settings/connections/$connectionId/edit'
  id:
    | '__root__'
    | '/'
    | '/_dashboard'
    | '/login'
    | '/_dashboard/connections'
    | '/_dashboard/queues'
    | '/_dashboard/connections/$connectionId'
    | '/_dashboard/queues/$queueName'
    | '/_dashboard/settings/connections'
    | '/api/auth/$'
    | '/_dashboard/settings/connections/new'
    | '/_dashboard/connections/$connectionId/queues/$queueName'
    | '/_dashboard/settings/connections/$connectionId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/queues': {
      id: '/_dashboard/queues'
      path: '/queues'
      fullPath: '/queues'
      preLoaderRoute: typeof DashboardQueuesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/connections': {
      id: '/_dashboard/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof DashboardConnectionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/settings/connections': {
      id: '/_dashboard/settings/connections'
      path: '/settings/connections'
      fullPath: '/settings/connections'
      preLoaderRoute: typeof DashboardSettingsConnectionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/queues/$queueName': {
      id: '/_dashboard/queues/$queueName'
      path: '/$queueName'
      fullPath: '/queues/$queueName'
      preLoaderRoute: typeof DashboardQueuesQueueNameRouteImport
      parentRoute: typeof DashboardQueuesRoute
    }
    '/_dashboard/connections/$connectionId': {
      id: '/_dashboard/connections/$connectionId'
      path: '/$connectionId'
      fullPath: '/connections/$connectionId'
      preLoaderRoute: typeof DashboardConnectionsConnectionIdRouteImport
      parentRoute: typeof DashboardConnectionsRoute
    }
    '/_dashboard/settings/connections/new': {
      id: '/_dashboard/settings/connections/new'
      path: '/new'
      fullPath: '/settings/connections/new'
      preLoaderRoute: typeof DashboardSettingsConnectionsNewRouteImport
      parentRoute: typeof DashboardSettingsConnectionsRoute
    }
    '/_dashboard/settings/connections/$connectionId/edit': {
      id: '/_dashboard/settings/connections/$connectionId/edit'
      path: '/$connectionId/edit'
      fullPath: '/settings/connections/$connectionId/edit'
      preLoaderRoute: typeof DashboardSettingsConnectionsConnectionIdEditRouteImport
      parentRoute: typeof DashboardSettingsConnectionsRoute
    }
    '/_dashboard/connections/$connectionId/queues/$queueName': {
      id: '/_dashboard/connections/$connectionId/queues/$queueName'
      path: '/queues/$queueName'
      fullPath: '/connections/$connectionId/queues/$queueName'
      preLoaderRoute: typeof DashboardConnectionsConnectionIdQueuesQueueNameRouteImport
      parentRoute: typeof DashboardConnectionsConnectionIdRoute
    }
  }
}

interface DashboardConnectionsConnectionIdRouteChildren {
  DashboardConnectionsConnectionIdQueuesQueueNameRoute: typeof DashboardConnectionsConnectionIdQueuesQueueNameRoute
}

const DashboardConnectionsConnectionIdRouteChildren: DashboardConnectionsConnectionIdRouteChildren =
  {
    DashboardConnectionsConnectionIdQueuesQueueNameRoute:
      DashboardConnectionsConnectionIdQueuesQueueNameRoute,
  }

const DashboardConnectionsConnectionIdRouteWithChildren =
  DashboardConnectionsConnectionIdRoute._addFileChildren(
    DashboardConnectionsConnectionIdRouteChildren,
  )

interface DashboardConnectionsRouteChildren {
  DashboardConnectionsConnectionIdRoute: typeof DashboardConnectionsConnectionIdRouteWithChildren
}

const DashboardConnectionsRouteChildren: DashboardConnectionsRouteChildren = {
  DashboardConnectionsConnectionIdRoute:
    DashboardConnectionsConnectionIdRouteWithChildren,
}

const DashboardConnectionsRouteWithChildren =
  DashboardConnectionsRoute._addFileChildren(DashboardConnectionsRouteChildren)

interface DashboardQueuesRouteChildren {
  DashboardQueuesQueueNameRoute: typeof DashboardQueuesQueueNameRoute
}

const DashboardQueuesRouteChildren: DashboardQueuesRouteChildren = {
  DashboardQueuesQueueNameRoute: DashboardQueuesQueueNameRoute,
}

const DashboardQueuesRouteWithChildren = DashboardQueuesRoute._addFileChildren(
  DashboardQueuesRouteChildren,
)

interface DashboardSettingsConnectionsRouteChildren {
  DashboardSettingsConnectionsNewRoute: typeof DashboardSettingsConnectionsNewRoute
  DashboardSettingsConnectionsConnectionIdEditRoute: typeof DashboardSettingsConnectionsConnectionIdEditRoute
}

const DashboardSettingsConnectionsRouteChildren: DashboardSettingsConnectionsRouteChildren =
  {
    DashboardSettingsConnectionsNewRoute: DashboardSettingsConnectionsNewRoute,
    DashboardSettingsConnectionsConnectionIdEditRoute:
      DashboardSettingsConnectionsConnectionIdEditRoute,
  }

const DashboardSettingsConnectionsRouteWithChildren =
  DashboardSettingsConnectionsRoute._addFileChildren(
    DashboardSettingsConnectionsRouteChildren,
  )

interface DashboardRouteChildren {
  DashboardConnectionsRoute: typeof DashboardConnectionsRouteWithChildren
  DashboardQueuesRoute: typeof DashboardQueuesRouteWithChildren
  DashboardSettingsConnectionsRoute: typeof DashboardSettingsConnectionsRouteWithChildren
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardConnectionsRoute: DashboardConnectionsRouteWithChildren,
  DashboardQueuesRoute: DashboardQueuesRouteWithChildren,
  DashboardSettingsConnectionsRoute:
    DashboardSettingsConnectionsRouteWithChildren,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
